### ISSUE TITLE
Pointers do not seem to work properly.

### ISSUE THREAD

**Issue by Kneesnap** [astrelsky/ghidra-emotionengine#2]
@astrelsky I hope everything is going well. I have an issue to report though.
It seems like many pointers are not interpretted correctly.

I compiled this code:
![image](https://user-images.githubusercontent.com/6562913/96192640-490b7580-0efb-11eb-861c-d088fe306ac2.png)

When disassembling in Ghidra, I get this:
![image](https://user-images.githubusercontent.com/6562913/96192591-2c6f3d80-0efb-11eb-963e-e7860fe50ced.png)

I notice that 0x221700 is exactly double the real pointer address. Seems like an issue with the plugin to me.

[cw_dbg_opt0.zip](https://github.com/astrelsky/ghidra-emotionengine/files/5388311/cw_dbg_opt0.zip)

**Comment by astrelsky** [comment]
So GitHub's auto link close feature thing has failed me.

I just removed all processing of `R_MIPS_HI16` and `R_MIPS_LO16` for now. If anything still doesn't seem right lmk.

**Comment by Kneesnap** [comment]
**EDIT:** I have moved this into a separate issue, #2.

Unfortunately the issue still exists somewhat.

This is the same code screenshotted above. It now successfully gets the name of the symbol, which when clicked navigates to the real string. It isn't ideal, but it's good enough for me.
![image](https://user-images.githubusercontent.com/6562913/96355155-6115fd00-1093-11eb-99cf-290eb82cab54.png)


However, I have another seemingly related issue (which is why I've re-opened this one) affecting the executable I'd actually like to reverse.

![image](https://user-images.githubusercontent.com/6562913/96355182-a2a6a800-1093-11eb-88da-5730477f2ba9.png)

![image](https://user-images.githubusercontent.com/6562913/96355271-940cc080-1094-11eb-94c0-b218bc6b56fa.png)

The addresses shown here (eg. $227BB8h) are not correct. 
I have not been able to figure out what the proper addresses are yet.

Both IDA and PCSX2's Debugger read some of these instructions different from Ghidra.
Ghidra:
![image](https://user-images.githubusercontent.com/6562913/96355270-8eaf7600-1094-11eb-80f7-5ab908ba43bc.png)
PCSX2 / IDA Pro:
![image](https://user-images.githubusercontent.com/6562913/96355433-7d676900-1096-11eb-9bf1-d9568dbd3a4e.png)

**Comment by astrelsky** [comment]
In order for the string value to be used in place of the symbol the data needs to be marked as constant. To do so right click on the data, go to the data sub menu, then settings and choose constant under mutability. This is standard ghidra behavior. I typically set the default mutability to constant for string datatypes and will use a char array when I know the data is mutable.

**Comment by Kneesnap** [comment]
This issue has not been fully resolved after all.

![image](https://user-images.githubusercontent.com/6562913/97062947-062c4c00-1552-11eb-8350-59a5a629b25b.png)
![image](https://user-images.githubusercontent.com/6562913/97062923-edbc3180-1551-11eb-9aea-3c7b451da13f.png)
![image](https://user-images.githubusercontent.com/6562913/97062938-f6ad0300-1551-11eb-9286-28d2df2189c4.png)

**Comment by Kneesnap** [comment]
Furthermore there appears to be an issue with function detection too. These addresses point to callback functions.
![image](https://user-images.githubusercontent.com/6562913/97063072-98cceb00-1552-11eb-8ab2-1c5b0393776a.png)
![image](https://user-images.githubusercontent.com/6562913/97063078-9d919f00-1552-11eb-9d71-8649be0e3022.png)

**Comment by astrelsky** [comment]
> This issue has not been fully resolved after all.
> 
> ![image](https://user-images.githubusercontent.com/6562913/97062947-062c4c00-1552-11eb-8350-59a5a629b25b.png)
> ![image](https://user-images.githubusercontent.com/6562913/97062923-edbc3180-1551-11eb-9aea-3c7b451da13f.png)
> ![image](https://user-images.githubusercontent.com/6562913/97062938-f6ad0300-1551-11eb-9286-28d2df2189c4.png)
> 
> 

Please show the mutability settings of the string data. Ghidra will only use the value of a string if it is marked as a constant. 

> Furthermore there appears to be an issue with function detection too. These addresses point to callback functions.
> ![image](https://user-images.githubusercontent.com/6562913/97063072-98cceb00-1552-11eb-8ab2-1c5b0393776a.png)
> ![image](https://user-images.githubusercontent.com/6562913/97063078-9d919f00-1552-11eb-9d71-8649be0e3022.png)
> 
> 



For the callback parameters, if the function signature has not been committed yet ghidra will still assume the types of the parameters. It is assuming it to be an integer type here instead of a pointer. Try defining the function signatures for `kcSetErrorHandler` and `kcSetTraceCallback`

**Comment by Kneesnap** [comment]
> Please show the mutability settings of the string data. Ghidra will only use the value of a string if it is marked as a constant.

![image](https://user-images.githubusercontent.com/6562913/97063768-7a68ee80-1556-11eb-8491-debdc2d4322e.png)

> For the callback parameters, if the function signature has not been committed yet ghidra will still assume the types of the parameters. It is assuming it to be an integer type here instead of a pointer. Try defining the function signatures for `kcSetErrorHandler` and `kcSetTraceCallback`

Ah, I see. That's my fault then.

**Comment by astrelsky** [comment]
Set the mutability to constant.
